name: Update Discord Class Names
on:
    schedule:
        - cron: "0 0 * * *" # Daily check
    workflow_dispatch:

permissions:
    pull-requests: write-all

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run Class Name Updater
              uses: fedeericodl/discord-update-classnames@main
              with:
                  files: "src/theme-nohover.css"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  target-branch: visual-refresh
                  commit-message: 'chore: update Discord class names (automated)'
                  pr-title: Classes Updates
